# permissions for end users to edit networkchaos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: networkchaos-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chaos-operator
    app.kubernetes.io/part-of: chaos-operator
    app.kubernetes.io/managed-by: kustomize
  name: networkchaos-editor-role
rules:
- apiGroups:
  - chaos.snappcloud.io
  resources:
  - networkchaos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.snappcloud.io
  resources:
  - networkchaos/status
  verbs:
  - get
