---
  name: build-release
  on:
    push:
      tags: [ v* ]
  
  jobs:
    docker:
      name: docker
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: docker/setup-qemu-action@v2
        - uses: docker/setup-buildx-action@v2
        - uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - uses: docker/metadata-action@v4
          id: meta
          with:
            images: ghcr.io/${{ github.repository }}
            tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=sha,prefix=
  
        - uses: docker/build-push-action@v2
          with:
            file: "Dockerfile"
            context: .
            platforms: linux/amd64
            push: true
            tags: |
              ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
    helm-chart:
      name: helm-chart
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: helmify
          run: make helm
        - name: Chart | Push
          uses: appany/helm-oci-chart-releaser@v0.3.0
          with:
            name: chaos-operator
            repository: ${{ github.repository }}/helm-charts
            tag: ${{ github.ref_name }}
            path: charts/chaos-operator # Default charts/{name}
            registry: ghcr.io
            registry_username:  ${{ github.repository_owner }}
            registry_password: ${{ secrets.GITHUB_TOKEN }}
          
    release:
      name: release
      runs-on: ubuntu-latest
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v3
        - name: release
          run: gh release create ${{ github.ref_name }} --generate-notes --verify-tag 
